# Generated by Django 5.0.6 on 2026-06-24 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Kata kunci pencarian', max_length=255)),
                ('parsed_params', models.JSONField(blank=True, default=dict, help_text='Parameter pencarian yang sudah diparse')),
                ('results_count', models.IntegerField(default=0, help_text='Jumlah hasil yang ditemukan')),
                ('searched_at', models.DateTimeField(auto_now_add=True, help_text='Waktu pencarian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='assistant_s_user_id_e6707a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nama produk', max_length=255)),
                ('product_url', models.URLField(blank=True, help_text='Link produk', max_length=500)),
                ('product_image', models.URLField(blank=True, help_text='URL gambar produk', max_length=500)),
                ('product_price', models.CharField(blank=True, help_text='Harga produk', max_length=50)),
                ('product_store', models.CharField(blank=True, help_text='Toko/penjual', max_length=100)),
                ('product_rating', models.CharField(blank=True, help_text='Rating produk', max_length=10)),
                ('product_data', models.JSONField(blank=True, default=dict, help_text='Data produk lengkap dalam format JSON')),
                ('notes', models.TextField(blank=True, help_text='Catatan pribadi tentang produk')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Waktu ditambahkan ke wishlist')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Waktu update terakhir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='assistant_w_user_id_0e2475_idx')],
                'unique_together': {('user', 'product_name')},
            },
        ),
    ]
