# Generated by Django 5.0.6 on 2026-06-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Nama halaman yang dikunjungi', max_length=255)),
                ('visitor_ip', models.CharField(blank=True, help_text='IP address pengunjung', max_length=45)),
                ('user_agent', models.TextField(blank=True, help_text='User agent browser')),
                ('visited_at', models.DateTimeField(auto_now_add=True, help_text='Waktu kunjungan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='assistant_p_visited_8d4252_idx'), models.Index(fields=['page', '-visited_at'], name='assistant_p_page_9f3ebd_idx')],
            },
        ),
    ]
